#cloud-config
package_update: true
package_upgrade: true

# Set hostname
hostname: ${hostname}
fqdn: ${hostname}

users:
  - name: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key_content}

packages:
- apt-utils
- vim
- python3
- python3-pip
- python3-venv

# Lazy install docker
runcmd:
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker docker
  - systemctl enable docker
  - systemctl start docker
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - mkdir -p /home/docker/git
  - chown -R docker:docker /home/docker/git
  - chmod -R 755 /home/docker/git
  - mkdir -p /mnt/docker-data
  - chown -R docker:docker /mnt/docker-data
  - chmod -R 755 /mnt/docker-data
