---
# Common tasks for FreshRSS management

- name: Install OCI CLI
  apt:
    name: oci-cli
    state: present
    update_cache: yes
  register: oci_install
  failed_when: oci_install.rc != 0

- name: Stop Docker Compose
  docker_compose:
    project_src: "{{ app_dir }}"
    state: absent
  register: docker_stop
  failed_when: docker_stop.rc != 0

- name: Start Docker Compose
  docker_compose:
    "{{ docker_compose_config }}"
  register: docker_start
  failed_when: docker_start.rc != 0

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  register: apt_update
  failed_when: apt_update.rc != 0

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes
  register: apt_upgrade
  failed_when: apt_upgrade.rc != 0

- name: Reboot and wait
  block:
    - name: Reboot the server
      reboot: "{{ reboot_config }}"
      register: reboot_result

    - name: Wait for server to come back
      wait_for_connection:
        delay: 30
        timeout: 300
      register: wait_result
  rescue:
    - name: Handle reboot failure
      debug:
        msg: "Reboot failed: {{ reboot_result.msg if reboot_result is defined else 'Unknown error' }}"
      failed_when: true 