---
# Pre-tasks for FreshRSS role

- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  changed_when: false
  failed_when: docker_check.rc != 0

- name: Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  changed_when: false
  failed_when: docker_compose_check.rc != 0

- name: Check if OCI CLI is installed
  command: oci --version
  register: oci_check
  changed_when: false
  failed_when: oci_check.rc != 0
  when: backup_file is defined

- name: Validate required variables
  assert:
    that:
      - app_dir is defined
      - git_repo is defined
      - backup_dir is defined
    fail_msg: "Required variables are not set" 