---
# Update tasks for FreshRSS

- name: Get current Docker image versions
  shell: docker-compose -f {{ app_dir }}/docker-compose.yml images
  register: current_versions
  changed_when: false

- name: Update Docker images
  docker_compose:
    project_src: "{{ app_dir }}"
    pull: yes
    build: no
  register: docker_update
  failed_when: docker_update.rc != 0

- name: Get new Docker image versions
  shell: docker-compose -f {{ app_dir }}/docker-compose.yml images
  register: new_versions
  changed_when: false

- name: Display version changes
  debug:
    msg: "Docker images updated from {{ current_versions.stdout }} to {{ new_versions.stdout }}"
  when: current_versions.stdout != new_versions.stdout 