---
# Tasks for backing up a single Docker Compose project

- name: Stop containers from project {{ project_name }}
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}"
    state: absent
  register: project_info

- name: Create backup of docker-data for project {{ project_name }}
  ansible.builtin.archive:
    path: "{{ data_dir }}"
    dest: "{{ backup_dir }}/{{ project_name }}-{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.tar.gz"
    format: gz
  register: backup_result

- name: Start containers from project {{ project_name }}
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}"
    state: present
  register: project_info

- name: Upload backup to OCI bucket for project {{ project_name }}
  oracle.oci.oci_object_storage_object:
    config_file_location: "{{ oci_config_file }}"
    bucket_name: "{{ oci_bucket_name }}"
    namespace_name: "{{ oci_namespace }}"
    object_name: "backups/{{ project_name }}/{{ backup_result.dest | basename }}"
    src: "{{ backup_result.dest }}"
    state: present
  environment:
    PATH: "{{ venv_path }}/bin:{{ ansible_env.PATH }}"
    PYTHONPATH: "{{ venv_path }}/lib/python3/dist-packages:{{ ansible_env.PYTHONPATH | default('') }}"
    VIRTUAL_ENV: "{{ venv_path }}"
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  register: upload_result

- name: Remove local backup file of the project {{ project_name }}
  ansible.builtin.file:
    path: "{{ backup_result.dest }}"
    state: absent
  when: upload_result.changed 