---
# Playbook to backup Docker Compose projects

- name: Backup Docker Projects
  hosts: all
  vars:
    setup_python_env: true  # Set to false to skip Python environment setup
  tasks:
    - name: Backup each project
      ansible.builtin.include_tasks: backup_project.yml
      loop: "{{ projects }}"
      loop_control:
        loop_var: project
      vars:
        config_dir: "{{ project.config_dir }}"
        data_dir: "{{ project.data_dir }}"
        project_name: "{{ project.name }}"
