---
galaxy_info:
  role_name: freshrss
  author: Your Name
  description: Role for deploying and managing FreshRSS
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - freshrss
    - rss
    - feed
    - docker
    - oci

dependencies: [] 