---
# Handlers for FreshRSS role

- name: restart docker compose
  docker_compose:
    project_src: "{{ app_dir }}"
    state: present
    build: no
    remove_orphans: yes
    pull: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart systemd
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docker
    - docker.socket 